// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/aircraft_war.proto

// Aircraft War 多人联机协议。
// 只用于 Protobuf 编解码，不用于 gRPC。

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 房间状态。房间只有在两名玩家都结束后才会进入 FINISHED。
type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_UNSPECIFIED RoomStatus = 0
	RoomStatus_ROOM_STATUS_WAITING     RoomStatus = 1
	RoomStatus_ROOM_STATUS_FULL        RoomStatus = 2
	RoomStatus_ROOM_STATUS_READY       RoomStatus = 3
	RoomStatus_ROOM_STATUS_PLAYING     RoomStatus = 4
	RoomStatus_ROOM_STATUS_FINISHED    RoomStatus = 5
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "ROOM_STATUS_UNSPECIFIED",
		1: "ROOM_STATUS_WAITING",
		2: "ROOM_STATUS_FULL",
		3: "ROOM_STATUS_READY",
		4: "ROOM_STATUS_PLAYING",
		5: "ROOM_STATUS_FINISHED",
	}
	RoomStatus_value = map[string]int32{
		"ROOM_STATUS_UNSPECIFIED": 0,
		"ROOM_STATUS_WAITING":     1,
		"ROOM_STATUS_FULL":        2,
		"ROOM_STATUS_READY":       3,
		"ROOM_STATUS_PLAYING":     4,
		"ROOM_STATUS_FINISHED":    5,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aircraft_war_proto_enumTypes[0].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_proto_aircraft_war_proto_enumTypes[0]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{0}
}

// 玩家在房间内的生命周期状态。
type PlayerStatus int32

const (
	PlayerStatus_PLAYER_STATUS_UNSPECIFIED PlayerStatus = 0
	PlayerStatus_PLAYER_STATUS_JOINED      PlayerStatus = 1
	PlayerStatus_PLAYER_STATUS_READY       PlayerStatus = 2
	PlayerStatus_PLAYER_STATUS_PLAYING     PlayerStatus = 3
	PlayerStatus_PLAYER_STATUS_FINISHED    PlayerStatus = 4
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "PLAYER_STATUS_UNSPECIFIED",
		1: "PLAYER_STATUS_JOINED",
		2: "PLAYER_STATUS_READY",
		3: "PLAYER_STATUS_PLAYING",
		4: "PLAYER_STATUS_FINISHED",
	}
	PlayerStatus_value = map[string]int32{
		"PLAYER_STATUS_UNSPECIFIED": 0,
		"PLAYER_STATUS_JOINED":      1,
		"PLAYER_STATUS_READY":       2,
		"PLAYER_STATUS_PLAYING":     3,
		"PLAYER_STATUS_FINISHED":    4,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aircraft_war_proto_enumTypes[1].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_proto_aircraft_war_proto_enumTypes[1]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{1}
}

// 敌机类型。服务端应以该类型为准计算得分。
type EnemyType int32

const (
	EnemyType_ENEMY_TYPE_UNSPECIFIED EnemyType = 0
	EnemyType_ENEMY_TYPE_MOB         EnemyType = 1
	EnemyType_ENEMY_TYPE_ELITE       EnemyType = 2
	EnemyType_ENEMY_TYPE_BOSS        EnemyType = 3
)

// Enum value maps for EnemyType.
var (
	EnemyType_name = map[int32]string{
		0: "ENEMY_TYPE_UNSPECIFIED",
		1: "ENEMY_TYPE_MOB",
		2: "ENEMY_TYPE_ELITE",
		3: "ENEMY_TYPE_BOSS",
	}
	EnemyType_value = map[string]int32{
		"ENEMY_TYPE_UNSPECIFIED": 0,
		"ENEMY_TYPE_MOB":         1,
		"ENEMY_TYPE_ELITE":       2,
		"ENEMY_TYPE_BOSS":        3,
	}
)

func (x EnemyType) Enum() *EnemyType {
	p := new(EnemyType)
	*p = x
	return p
}

func (x EnemyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnemyType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aircraft_war_proto_enumTypes[2].Descriptor()
}

func (EnemyType) Type() protoreflect.EnumType {
	return &file_proto_aircraft_war_proto_enumTypes[2]
}

func (x EnemyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnemyType.Descriptor instead.
func (EnemyType) EnumDescriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{2}
}

// 房间共享难度。单机可继续使用本地难度字符串，但联机房间必须使用统一枚举同步。
type RoomDifficulty int32

const (
	RoomDifficulty_ROOM_DIFFICULTY_UNSPECIFIED RoomDifficulty = 0
	RoomDifficulty_ROOM_DIFFICULTY_EASY        RoomDifficulty = 1
	RoomDifficulty_ROOM_DIFFICULTY_NORMAL      RoomDifficulty = 2
	RoomDifficulty_ROOM_DIFFICULTY_HARD        RoomDifficulty = 3
)

// Enum value maps for RoomDifficulty.
var (
	RoomDifficulty_name = map[int32]string{
		0: "ROOM_DIFFICULTY_UNSPECIFIED",
		1: "ROOM_DIFFICULTY_EASY",
		2: "ROOM_DIFFICULTY_NORMAL",
		3: "ROOM_DIFFICULTY_HARD",
	}
	RoomDifficulty_value = map[string]int32{
		"ROOM_DIFFICULTY_UNSPECIFIED": 0,
		"ROOM_DIFFICULTY_EASY":        1,
		"ROOM_DIFFICULTY_NORMAL":      2,
		"ROOM_DIFFICULTY_HARD":        3,
	}
)

func (x RoomDifficulty) Enum() *RoomDifficulty {
	p := new(RoomDifficulty)
	*p = x
	return p
}

func (x RoomDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aircraft_war_proto_enumTypes[3].Descriptor()
}

func (RoomDifficulty) Type() protoreflect.EnumType {
	return &file_proto_aircraft_war_proto_enumTypes[3]
}

func (x RoomDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomDifficulty.Descriptor instead.
func (RoomDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{3}
}

// 从当前玩家视角看到的对局结果。
type GameResultType int32

const (
	GameResultType_GAME_RESULT_UNSPECIFIED GameResultType = 0
	GameResultType_GAME_RESULT_WIN         GameResultType = 1
	GameResultType_GAME_RESULT_LOSE        GameResultType = 2
	GameResultType_GAME_RESULT_DRAW        GameResultType = 3
)

// Enum value maps for GameResultType.
var (
	GameResultType_name = map[int32]string{
		0: "GAME_RESULT_UNSPECIFIED",
		1: "GAME_RESULT_WIN",
		2: "GAME_RESULT_LOSE",
		3: "GAME_RESULT_DRAW",
	}
	GameResultType_value = map[string]int32{
		"GAME_RESULT_UNSPECIFIED": 0,
		"GAME_RESULT_WIN":         1,
		"GAME_RESULT_LOSE":        2,
		"GAME_RESULT_DRAW":        3,
	}
)

func (x GameResultType) Enum() *GameResultType {
	p := new(GameResultType)
	*p = x
	return p
}

func (x GameResultType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameResultType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aircraft_war_proto_enumTypes[4].Descriptor()
}

func (GameResultType) Type() protoreflect.EnumType {
	return &file_proto_aircraft_war_proto_enumTypes[4]
}

func (x GameResultType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameResultType.Descriptor instead.
func (GameResultType) EnumDescriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{4}
}

// 玩家结束原因。用于区分主动正常结束和服务端判定掉线结束。
type PlayerFinishReason int32

const (
	PlayerFinishReason_PLAYER_FINISH_REASON_UNSPECIFIED  PlayerFinishReason = 0
	PlayerFinishReason_PLAYER_FINISH_REASON_NORMAL       PlayerFinishReason = 1
	PlayerFinishReason_PLAYER_FINISH_REASON_DISCONNECTED PlayerFinishReason = 2
)

// Enum value maps for PlayerFinishReason.
var (
	PlayerFinishReason_name = map[int32]string{
		0: "PLAYER_FINISH_REASON_UNSPECIFIED",
		1: "PLAYER_FINISH_REASON_NORMAL",
		2: "PLAYER_FINISH_REASON_DISCONNECTED",
	}
	PlayerFinishReason_value = map[string]int32{
		"PLAYER_FINISH_REASON_UNSPECIFIED":  0,
		"PLAYER_FINISH_REASON_NORMAL":       1,
		"PLAYER_FINISH_REASON_DISCONNECTED": 2,
	}
)

func (x PlayerFinishReason) Enum() *PlayerFinishReason {
	p := new(PlayerFinishReason)
	*p = x
	return p
}

func (x PlayerFinishReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerFinishReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aircraft_war_proto_enumTypes[5].Descriptor()
}

func (PlayerFinishReason) Type() protoreflect.EnumType {
	return &file_proto_aircraft_war_proto_enumTypes[5]
}

func (x PlayerFinishReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerFinishReason.Descriptor instead.
func (PlayerFinishReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{5}
}

// 房间中的玩家基础信息。
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Status        PlayerStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=hitsz.aircraftwar.backend.PlayerStatus" json:"status,omitempty"`
	IsHost        bool                   `protobuf:"varint,3,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	AvatarId      string                 `protobuf:"bytes,4,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_aircraft_war_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_PLAYER_STATUS_UNSPECIFIED
}

func (x *Player) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

func (x *Player) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

// 房间基础信息。双人房间通过 players 表达当前成员。
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Status        RoomStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=hitsz.aircraftwar.backend.RoomStatus" json:"status,omitempty"`
	Players       []*Player              `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Difficulty    RoomDifficulty         `protobuf:"varint,4,opt,name=difficulty,proto3,enum=hitsz.aircraftwar.backend.RoomDifficulty" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_aircraft_war_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *Room) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Room) GetDifficulty() RoomDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return RoomDifficulty_ROOM_DIFFICULTY_UNSPECIFIED
}

// 房间内单个玩家的实时分数状态。
// 用于比分广播和状态恢复查询。
type RoomPlayerScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Finished      bool                   `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	Status        PlayerStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=hitsz.aircraftwar.backend.PlayerStatus" json:"status,omitempty"`
	FinishReason  PlayerFinishReason     `protobuf:"varint,5,opt,name=finish_reason,json=finishReason,proto3,enum=hitsz.aircraftwar.backend.PlayerFinishReason" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomPlayerScore) Reset() {
	*x = RoomPlayerScore{}
	mi := &file_proto_aircraft_war_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomPlayerScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayerScore) ProtoMessage() {}

func (x *RoomPlayerScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayerScore.ProtoReflect.Descriptor instead.
func (*RoomPlayerScore) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{2}
}

func (x *RoomPlayerScore) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RoomPlayerScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RoomPlayerScore) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *RoomPlayerScore) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_PLAYER_STATUS_UNSPECIFIED
}

func (x *RoomPlayerScore) GetFinishReason() PlayerFinishReason {
	if x != nil {
		return x.FinishReason
	}
	return PlayerFinishReason_PLAYER_FINISH_REASON_UNSPECIFIED
}

// 一局对战的最终结果快照。
type RoomResult struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoomId              string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerAUsername     string                 `protobuf:"bytes,2,opt,name=player_a_username,json=playerAUsername,proto3" json:"player_a_username,omitempty"`
	PlayerBUsername     string                 `protobuf:"bytes,3,opt,name=player_b_username,json=playerBUsername,proto3" json:"player_b_username,omitempty"`
	PlayerAScore        int32                  `protobuf:"varint,4,opt,name=player_a_score,json=playerAScore,proto3" json:"player_a_score,omitempty"`
	PlayerBScore        int32                  `protobuf:"varint,5,opt,name=player_b_score,json=playerBScore,proto3" json:"player_b_score,omitempty"`
	WinnerUsername      string                 `protobuf:"bytes,6,opt,name=winner_username,json=winnerUsername,proto3" json:"winner_username,omitempty"`
	SelfResult          GameResultType         `protobuf:"varint,7,opt,name=self_result,json=selfResult,proto3,enum=hitsz.aircraftwar.backend.GameResultType" json:"self_result,omitempty"`
	FinishedAt          int64                  `protobuf:"varint,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	PlayerAFinishReason PlayerFinishReason     `protobuf:"varint,9,opt,name=player_a_finish_reason,json=playerAFinishReason,proto3,enum=hitsz.aircraftwar.backend.PlayerFinishReason" json:"player_a_finish_reason,omitempty"`
	PlayerBFinishReason PlayerFinishReason     `protobuf:"varint,10,opt,name=player_b_finish_reason,json=playerBFinishReason,proto3,enum=hitsz.aircraftwar.backend.PlayerFinishReason" json:"player_b_finish_reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RoomResult) Reset() {
	*x = RoomResult{}
	mi := &file_proto_aircraft_war_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResult) ProtoMessage() {}

func (x *RoomResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResult.ProtoReflect.Descriptor instead.
func (*RoomResult) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{3}
}

func (x *RoomResult) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomResult) GetPlayerAUsername() string {
	if x != nil {
		return x.PlayerAUsername
	}
	return ""
}

func (x *RoomResult) GetPlayerBUsername() string {
	if x != nil {
		return x.PlayerBUsername
	}
	return ""
}

func (x *RoomResult) GetPlayerAScore() int32 {
	if x != nil {
		return x.PlayerAScore
	}
	return 0
}

func (x *RoomResult) GetPlayerBScore() int32 {
	if x != nil {
		return x.PlayerBScore
	}
	return 0
}

func (x *RoomResult) GetWinnerUsername() string {
	if x != nil {
		return x.WinnerUsername
	}
	return ""
}

func (x *RoomResult) GetSelfResult() GameResultType {
	if x != nil {
		return x.SelfResult
	}
	return GameResultType_GAME_RESULT_UNSPECIFIED
}

func (x *RoomResult) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *RoomResult) GetPlayerAFinishReason() PlayerFinishReason {
	if x != nil {
		return x.PlayerAFinishReason
	}
	return PlayerFinishReason_PLAYER_FINISH_REASON_UNSPECIFIED
}

func (x *RoomResult) GetPlayerBFinishReason() PlayerFinishReason {
	if x != nil {
		return x.PlayerBFinishReason
	}
	return PlayerFinishReason_PLAYER_FINISH_REASON_UNSPECIFIED
}

// 全服排行榜条目。按 best_score 排序。
type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	BestScore     int32                  `protobuf:"varint,2,opt,name=best_score,json=bestScore,proto3" json:"best_score,omitempty"`
	WinCount      int32                  `protobuf:"varint,3,opt,name=win_count,json=winCount,proto3" json:"win_count,omitempty"`
	GameCount     int32                  `protobuf:"varint,4,opt,name=game_count,json=gameCount,proto3" json:"game_count,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AvatarId      string                 `protobuf:"bytes,6,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_proto_aircraft_war_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{4}
}

func (x *LeaderboardEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaderboardEntry) GetBestScore() int32 {
	if x != nil {
		return x.BestScore
	}
	return 0
}

func (x *LeaderboardEntry) GetWinCount() int32 {
	if x != nil {
		return x.WinCount
	}
	return 0
}

func (x *LeaderboardEntry) GetGameCount() int32 {
	if x != nil {
		return x.GameCount
	}
	return 0
}

func (x *LeaderboardEntry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *LeaderboardEntry) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

// HTTP: 创建房间。
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AvatarId      string                 `protobuf:"bytes,2,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	Difficulty    RoomDifficulty         `protobuf:"varint,3,opt,name=difficulty,proto3,enum=hitsz.aircraftwar.backend.RoomDifficulty" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_aircraft_war_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoomRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateRoomRequest) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

func (x *CreateRoomRequest) GetDifficulty() RoomDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return RoomDifficulty_ROOM_DIFFICULTY_UNSPECIFIED
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Self          *Player                `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_proto_aircraft_war_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *CreateRoomResponse) GetSelf() *Player {
	if x != nil {
		return x.Self
	}
	return nil
}

// HTTP: 加入房间。
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarId      string                 `protobuf:"bytes,3,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_proto_aircraft_war_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{7}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *JoinRoomRequest) GetAvatarId() string {
	if x != nil {
		return x.AvatarId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Self          *Player                `protobuf:"bytes,2,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_proto_aircraft_war_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *JoinRoomResponse) GetSelf() *Player {
	if x != nil {
		return x.Self
	}
	return nil
}

// HTTP: 玩家准备。
type ReadyRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRoomRequest) Reset() {
	*x = ReadyRoomRequest{}
	mi := &file_proto_aircraft_war_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRoomRequest) ProtoMessage() {}

func (x *ReadyRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRoomRequest.ProtoReflect.Descriptor instead.
func (*ReadyRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{9}
}

func (x *ReadyRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReadyRoomRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ReadyRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRoomResponse) Reset() {
	*x = ReadyRoomResponse{}
	mi := &file_proto_aircraft_war_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRoomResponse) ProtoMessage() {}

func (x *ReadyRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRoomResponse.ProtoReflect.Descriptor instead.
func (*ReadyRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{10}
}

func (x *ReadyRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// HTTP: 房主更新房间共享难度。
type UpdateRoomDifficultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Difficulty    RoomDifficulty         `protobuf:"varint,3,opt,name=difficulty,proto3,enum=hitsz.aircraftwar.backend.RoomDifficulty" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomDifficultyRequest) Reset() {
	*x = UpdateRoomDifficultyRequest{}
	mi := &file_proto_aircraft_war_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomDifficultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomDifficultyRequest) ProtoMessage() {}

func (x *UpdateRoomDifficultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomDifficultyRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomDifficultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRoomDifficultyRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateRoomDifficultyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateRoomDifficultyRequest) GetDifficulty() RoomDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return RoomDifficulty_ROOM_DIFFICULTY_UNSPECIFIED
}

type UpdateRoomDifficultyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomDifficultyResponse) Reset() {
	*x = UpdateRoomDifficultyResponse{}
	mi := &file_proto_aircraft_war_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomDifficultyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomDifficultyResponse) ProtoMessage() {}

func (x *UpdateRoomDifficultyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomDifficultyResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomDifficultyResponse) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRoomDifficultyResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// HTTP: 房主开始游戏。
type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_proto_aircraft_war_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{13}
}

func (x *StartGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartGameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Started       bool                   `protobuf:"varint,2,opt,name=started,proto3" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_proto_aircraft_war_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{14}
}

func (x *StartGameResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *StartGameResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

// HTTP: 查询房间最终结算。
type GetRoomResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResultRequest) Reset() {
	*x = GetRoomResultRequest{}
	mi := &file_proto_aircraft_war_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResultRequest) ProtoMessage() {}

func (x *GetRoomResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResultRequest.ProtoReflect.Descriptor instead.
func (*GetRoomResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{15}
}

func (x *GetRoomResultRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomResultRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetRoomResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *RoomResult            `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResultResponse) Reset() {
	*x = GetRoomResultResponse{}
	mi := &file_proto_aircraft_war_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResultResponse) ProtoMessage() {}

func (x *GetRoomResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResultResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{16}
}

func (x *GetRoomResultResponse) GetResult() *RoomResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// HTTP: 查询房间当前状态。
// 用于掉线玩家恢复网络后确认自己是否已被判定结束。
type GetRoomStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomStateRequest) Reset() {
	*x = GetRoomStateRequest{}
	mi := &file_proto_aircraft_war_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStateRequest) ProtoMessage() {}

func (x *GetRoomStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStateRequest.ProtoReflect.Descriptor instead.
func (*GetRoomStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{17}
}

func (x *GetRoomStateRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomStateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetRoomStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 房间基础状态。
	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// 双方当前分数和结束状态。
	Scores []*RoomPlayerScore `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
	// 房间是否已经整体结束。
	RoomFinished bool `protobuf:"varint,3,opt,name=room_finished,json=roomFinished,proto3" json:"room_finished,omitempty"`
	// 若房间已结束，可直接附带结算结果。
	Result        *RoomResult `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomStateResponse) Reset() {
	*x = GetRoomStateResponse{}
	mi := &file_proto_aircraft_war_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomStateResponse) ProtoMessage() {}

func (x *GetRoomStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomStateResponse.ProtoReflect.Descriptor instead.
func (*GetRoomStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{18}
}

func (x *GetRoomStateResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetRoomStateResponse) GetScores() []*RoomPlayerScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *GetRoomStateResponse) GetRoomFinished() bool {
	if x != nil {
		return x.RoomFinished
	}
	return false
}

func (x *GetRoomStateResponse) GetResult() *RoomResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// HTTP: 查询全服排行榜。
type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_proto_aircraft_war_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{19}
}

func (x *GetLeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLeaderboardRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_proto_aircraft_war_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{20}
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// WS: 玩家击败敌机事件。
// score_delta 只用于日志或调试，服务端应以 enemy_type 为准计分。
type PlayerDefeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	EnemyType     EnemyType              `protobuf:"varint,3,opt,name=enemy_type,json=enemyType,proto3,enum=hitsz.aircraftwar.backend.EnemyType" json:"enemy_type,omitempty"`
	ScoreDelta    int32                  `protobuf:"varint,4,opt,name=score_delta,json=scoreDelta,proto3" json:"score_delta,omitempty"`
	ClientEventId string                 `protobuf:"bytes,5,opt,name=client_event_id,json=clientEventId,proto3" json:"client_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDefeatEvent) Reset() {
	*x = PlayerDefeatEvent{}
	mi := &file_proto_aircraft_war_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDefeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDefeatEvent) ProtoMessage() {}

func (x *PlayerDefeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDefeatEvent.ProtoReflect.Descriptor instead.
func (*PlayerDefeatEvent) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{21}
}

func (x *PlayerDefeatEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlayerDefeatEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerDefeatEvent) GetEnemyType() EnemyType {
	if x != nil {
		return x.EnemyType
	}
	return EnemyType_ENEMY_TYPE_UNSPECIFIED
}

func (x *PlayerDefeatEvent) GetScoreDelta() int32 {
	if x != nil {
		return x.ScoreDelta
	}
	return 0
}

func (x *PlayerDefeatEvent) GetClientEventId() string {
	if x != nil {
		return x.ClientEventId
	}
	return ""
}

// WS: 对战期心跳。
// 建议每 3 秒发送一次；服务端 9 秒超时，额外复检 3 秒。
type PlayerHeartbeatEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RoomId   string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 客户端发送心跳时的本地时间戳，便于排查延迟和抖动。
	ClientSentAt int64 `protobuf:"varint,3,opt,name=client_sent_at,json=clientSentAt,proto3" json:"client_sent_at,omitempty"`
	// 客户端递增序号，便于埋点排查丢包或乱序。
	Sequence      int64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerHeartbeatEvent) Reset() {
	*x = PlayerHeartbeatEvent{}
	mi := &file_proto_aircraft_war_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerHeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerHeartbeatEvent) ProtoMessage() {}

func (x *PlayerHeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerHeartbeatEvent.ProtoReflect.Descriptor instead.
func (*PlayerHeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerHeartbeatEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlayerHeartbeatEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerHeartbeatEvent) GetClientSentAt() int64 {
	if x != nil {
		return x.ClientSentAt
	}
	return 0
}

func (x *PlayerHeartbeatEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// WS: 玩家主动上报本地游戏结束。
type PlayerGameOverEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FinalScore    int32                  `protobuf:"varint,3,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGameOverEvent) Reset() {
	*x = PlayerGameOverEvent{}
	mi := &file_proto_aircraft_war_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGameOverEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGameOverEvent) ProtoMessage() {}

func (x *PlayerGameOverEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGameOverEvent.ProtoReflect.Descriptor instead.
func (*PlayerGameOverEvent) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{23}
}

func (x *PlayerGameOverEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PlayerGameOverEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerGameOverEvent) GetFinalScore() int32 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

func (x *PlayerGameOverEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// WS: 服务端广播房间最新比分。
// 即使一名玩家已掉线结束，只要房间未结束，仍继续广播另一名玩家分数变化。
type ScoreBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Scores        []*RoomPlayerScore     `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreBroadcast) Reset() {
	*x = ScoreBroadcast{}
	mi := &file_proto_aircraft_war_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreBroadcast) ProtoMessage() {}

func (x *ScoreBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreBroadcast.ProtoReflect.Descriptor instead.
func (*ScoreBroadcast) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{24}
}

func (x *ScoreBroadcast) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ScoreBroadcast) GetScores() []*RoomPlayerScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *ScoreBroadcast) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// WS: 服务端广播完整房间状态快照。
// 用于房间成员变化、准备状态变化、开始、结束以及重连后状态恢复。
type RoomStateBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Scores        []*RoomPlayerScore     `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
	RoomFinished  bool                   `protobuf:"varint,3,opt,name=room_finished,json=roomFinished,proto3" json:"room_finished,omitempty"`
	Result        *RoomResult            `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomStateBroadcast) Reset() {
	*x = RoomStateBroadcast{}
	mi := &file_proto_aircraft_war_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomStateBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomStateBroadcast) ProtoMessage() {}

func (x *RoomStateBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomStateBroadcast.ProtoReflect.Descriptor instead.
func (*RoomStateBroadcast) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{25}
}

func (x *RoomStateBroadcast) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *RoomStateBroadcast) GetScores() []*RoomPlayerScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *RoomStateBroadcast) GetRoomFinished() bool {
	if x != nil {
		return x.RoomFinished
	}
	return false
}

func (x *RoomStateBroadcast) GetResult() *RoomResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RoomStateBroadcast) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// WS: 当两名玩家都结束后，服务端广播整局最终完成。
type GameFinishedBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Finished      bool                   `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"`
	Result        *RoomResult            `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameFinishedBroadcast) Reset() {
	*x = GameFinishedBroadcast{}
	mi := &file_proto_aircraft_war_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameFinishedBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFinishedBroadcast) ProtoMessage() {}

func (x *GameFinishedBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFinishedBroadcast.ProtoReflect.Descriptor instead.
func (*GameFinishedBroadcast) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{26}
}

func (x *GameFinishedBroadcast) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameFinishedBroadcast) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *GameFinishedBroadcast) GetResult() *RoomResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// WS: WebSocket 二进制帧统一包裹消息。
// 一条 WebSocket binary frame 对应一个 WsMessage。
// 客户端与服务端都只通过该消息承载具体的 WS 事件载荷。
type WsMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WsMessage_PlayerHeartbeatEvent
	//	*WsMessage_PlayerDefeatEvent
	//	*WsMessage_PlayerGameOverEvent
	//	*WsMessage_ScoreBroadcast
	//	*WsMessage_GameFinishedBroadcast
	//	*WsMessage_RoomStateBroadcast
	Payload       isWsMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsMessage) Reset() {
	*x = WsMessage{}
	mi := &file_proto_aircraft_war_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsMessage) ProtoMessage() {}

func (x *WsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aircraft_war_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsMessage.ProtoReflect.Descriptor instead.
func (*WsMessage) Descriptor() ([]byte, []int) {
	return file_proto_aircraft_war_proto_rawDescGZIP(), []int{27}
}

func (x *WsMessage) GetPayload() isWsMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsMessage) GetPlayerHeartbeatEvent() *PlayerHeartbeatEvent {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_PlayerHeartbeatEvent); ok {
			return x.PlayerHeartbeatEvent
		}
	}
	return nil
}

func (x *WsMessage) GetPlayerDefeatEvent() *PlayerDefeatEvent {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_PlayerDefeatEvent); ok {
			return x.PlayerDefeatEvent
		}
	}
	return nil
}

func (x *WsMessage) GetPlayerGameOverEvent() *PlayerGameOverEvent {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_PlayerGameOverEvent); ok {
			return x.PlayerGameOverEvent
		}
	}
	return nil
}

func (x *WsMessage) GetScoreBroadcast() *ScoreBroadcast {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_ScoreBroadcast); ok {
			return x.ScoreBroadcast
		}
	}
	return nil
}

func (x *WsMessage) GetGameFinishedBroadcast() *GameFinishedBroadcast {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_GameFinishedBroadcast); ok {
			return x.GameFinishedBroadcast
		}
	}
	return nil
}

func (x *WsMessage) GetRoomStateBroadcast() *RoomStateBroadcast {
	if x != nil {
		if x, ok := x.Payload.(*WsMessage_RoomStateBroadcast); ok {
			return x.RoomStateBroadcast
		}
	}
	return nil
}

type isWsMessage_Payload interface {
	isWsMessage_Payload()
}

type WsMessage_PlayerHeartbeatEvent struct {
	PlayerHeartbeatEvent *PlayerHeartbeatEvent `protobuf:"bytes,1,opt,name=player_heartbeat_event,json=playerHeartbeatEvent,proto3,oneof"`
}

type WsMessage_PlayerDefeatEvent struct {
	PlayerDefeatEvent *PlayerDefeatEvent `protobuf:"bytes,2,opt,name=player_defeat_event,json=playerDefeatEvent,proto3,oneof"`
}

type WsMessage_PlayerGameOverEvent struct {
	PlayerGameOverEvent *PlayerGameOverEvent `protobuf:"bytes,3,opt,name=player_game_over_event,json=playerGameOverEvent,proto3,oneof"`
}

type WsMessage_ScoreBroadcast struct {
	ScoreBroadcast *ScoreBroadcast `protobuf:"bytes,4,opt,name=score_broadcast,json=scoreBroadcast,proto3,oneof"`
}

type WsMessage_GameFinishedBroadcast struct {
	GameFinishedBroadcast *GameFinishedBroadcast `protobuf:"bytes,5,opt,name=game_finished_broadcast,json=gameFinishedBroadcast,proto3,oneof"`
}

type WsMessage_RoomStateBroadcast struct {
	RoomStateBroadcast *RoomStateBroadcast `protobuf:"bytes,6,opt,name=room_state_broadcast,json=roomStateBroadcast,proto3,oneof"`
}

func (*WsMessage_PlayerHeartbeatEvent) isWsMessage_Payload() {}

func (*WsMessage_PlayerDefeatEvent) isWsMessage_Payload() {}

func (*WsMessage_PlayerGameOverEvent) isWsMessage_Payload() {}

func (*WsMessage_ScoreBroadcast) isWsMessage_Payload() {}

func (*WsMessage_GameFinishedBroadcast) isWsMessage_Payload() {}

func (*WsMessage_RoomStateBroadcast) isWsMessage_Payload() {}

var File_proto_aircraft_war_proto protoreflect.FileDescriptor

const file_proto_aircraft_war_proto_rawDesc = "" +
	"\n" +
	"\x18proto/aircraft_war.proto\x12\x19hitsz.aircraftwar.backend\"\x9b\x01\n" +
	"\x06Player\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12?\n" +
	"\x06status\x18\x02 \x01(\x0e2'.hitsz.aircraftwar.backend.PlayerStatusR\x06status\x12\x17\n" +
	"\ais_host\x18\x03 \x01(\bR\x06isHost\x12\x1b\n" +
	"\tavatar_id\x18\x04 \x01(\tR\bavatarId\"\xe6\x01\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.hitsz.aircraftwar.backend.RoomStatusR\x06status\x12;\n" +
	"\aplayers\x18\x03 \x03(\v2!.hitsz.aircraftwar.backend.PlayerR\aplayers\x12I\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x0e2).hitsz.aircraftwar.backend.RoomDifficultyR\n" +
	"difficulty\"\xf4\x01\n" +
	"\x0fRoomPlayerScore\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\x12?\n" +
	"\x06status\x18\x04 \x01(\x0e2'.hitsz.aircraftwar.backend.PlayerStatusR\x06status\x12R\n" +
	"\rfinish_reason\x18\x05 \x01(\x0e2-.hitsz.aircraftwar.backend.PlayerFinishReasonR\ffinishReason\"\xa7\x04\n" +
	"\n" +
	"RoomResult\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12*\n" +
	"\x11player_a_username\x18\x02 \x01(\tR\x0fplayerAUsername\x12*\n" +
	"\x11player_b_username\x18\x03 \x01(\tR\x0fplayerBUsername\x12$\n" +
	"\x0eplayer_a_score\x18\x04 \x01(\x05R\fplayerAScore\x12$\n" +
	"\x0eplayer_b_score\x18\x05 \x01(\x05R\fplayerBScore\x12'\n" +
	"\x0fwinner_username\x18\x06 \x01(\tR\x0ewinnerUsername\x12J\n" +
	"\vself_result\x18\a \x01(\x0e2).hitsz.aircraftwar.backend.GameResultTypeR\n" +
	"selfResult\x12\x1f\n" +
	"\vfinished_at\x18\b \x01(\x03R\n" +
	"finishedAt\x12b\n" +
	"\x16player_a_finish_reason\x18\t \x01(\x0e2-.hitsz.aircraftwar.backend.PlayerFinishReasonR\x13playerAFinishReason\x12b\n" +
	"\x16player_b_finish_reason\x18\n" +
	" \x01(\x0e2-.hitsz.aircraftwar.backend.PlayerFinishReasonR\x13playerBFinishReason\"\xc5\x01\n" +
	"\x10LeaderboardEntry\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"best_score\x18\x02 \x01(\x05R\tbestScore\x12\x1b\n" +
	"\twin_count\x18\x03 \x01(\x05R\bwinCount\x12\x1d\n" +
	"\n" +
	"game_count\x18\x04 \x01(\x05R\tgameCount\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\tavatar_id\x18\x06 \x01(\tR\bavatarId\"\x97\x01\n" +
	"\x11CreateRoomRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tavatar_id\x18\x02 \x01(\tR\bavatarId\x12I\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\x0e2).hitsz.aircraftwar.backend.RoomDifficultyR\n" +
	"difficulty\"\x80\x01\n" +
	"\x12CreateRoomResponse\x123\n" +
	"\x04room\x18\x01 \x01(\v2\x1f.hitsz.aircraftwar.backend.RoomR\x04room\x125\n" +
	"\x04self\x18\x02 \x01(\v2!.hitsz.aircraftwar.backend.PlayerR\x04self\"c\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tavatar_id\x18\x03 \x01(\tR\bavatarId\"~\n" +
	"\x10JoinRoomResponse\x123\n" +
	"\x04room\x18\x01 \x01(\v2\x1f.hitsz.aircraftwar.backend.RoomR\x04room\x125\n" +
	"\x04self\x18\x02 \x01(\v2!.hitsz.aircraftwar.backend.PlayerR\x04self\"G\n" +
	"\x10ReadyRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"H\n" +
	"\x11ReadyRoomResponse\x123\n" +
	"\x04room\x18\x01 \x01(\v2\x1f.hitsz.aircraftwar.backend.RoomR\x04room\"\x9d\x01\n" +
	"\x1bUpdateRoomDifficultyRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12I\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\x0e2).hitsz.aircraftwar.backend.RoomDifficultyR\n" +
	"difficulty\"S\n" +
	"\x1cUpdateRoomDifficultyResponse\x123\n" +
	"\x04room\x18\x01 \x01(\v2\x1f.hitsz.aircraftwar.backend.RoomR\x04room\"G\n" +
	"\x10StartGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"b\n" +
	"\x11StartGameResponse\x123\n" +
	"\x04room\x18\x01 \x01(\v2\x1f.hitsz.aircraftwar.backend.RoomR\x04room\x12\x18\n" +
	"\astarted\x18\x02 \x01(\bR\astarted\"K\n" +
	"\x14GetRoomResultRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"V\n" +
	"\x15GetRoomResultResponse\x12=\n" +
	"\x06result\x18\x01 \x01(\v2%.hitsz.aircraftwar.backend.RoomResultR\x06result\"J\n" +
	"\x13GetRoomStateRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\xf3\x01\n" +
	"\x14GetRoomStateResponse\x123\n" +
	"\x04room\x18\x01 \x01(\v2\x1f.hitsz.aircraftwar.backend.RoomR\x04room\x12B\n" +
	"\x06scores\x18\x02 \x03(\v2*.hitsz.aircraftwar.backend.RoomPlayerScoreR\x06scores\x12#\n" +
	"\rroom_finished\x18\x03 \x01(\bR\froomFinished\x12=\n" +
	"\x06result\x18\x04 \x01(\v2%.hitsz.aircraftwar.backend.RoomResultR\x06result\"E\n" +
	"\x15GetLeaderboardRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"_\n" +
	"\x16GetLeaderboardResponse\x12E\n" +
	"\aentries\x18\x01 \x03(\v2+.hitsz.aircraftwar.backend.LeaderboardEntryR\aentries\"\xd6\x01\n" +
	"\x11PlayerDefeatEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12C\n" +
	"\n" +
	"enemy_type\x18\x03 \x01(\x0e2$.hitsz.aircraftwar.backend.EnemyTypeR\tenemyType\x12\x1f\n" +
	"\vscore_delta\x18\x04 \x01(\x05R\n" +
	"scoreDelta\x12&\n" +
	"\x0fclient_event_id\x18\x05 \x01(\tR\rclientEventId\"\x8d\x01\n" +
	"\x14PlayerHeartbeatEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12$\n" +
	"\x0eclient_sent_at\x18\x03 \x01(\x03R\fclientSentAt\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\"\x83\x01\n" +
	"\x13PlayerGameOverEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\vfinal_score\x18\x03 \x01(\x05R\n" +
	"finalScore\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x8c\x01\n" +
	"\x0eScoreBroadcast\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12B\n" +
	"\x06scores\x18\x02 \x03(\v2*.hitsz.aircraftwar.backend.RoomPlayerScoreR\x06scores\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\"\x90\x02\n" +
	"\x12RoomStateBroadcast\x123\n" +
	"\x04room\x18\x01 \x01(\v2\x1f.hitsz.aircraftwar.backend.RoomR\x04room\x12B\n" +
	"\x06scores\x18\x02 \x03(\v2*.hitsz.aircraftwar.backend.RoomPlayerScoreR\x06scores\x12#\n" +
	"\rroom_finished\x18\x03 \x01(\bR\froomFinished\x12=\n" +
	"\x06result\x18\x04 \x01(\v2%.hitsz.aircraftwar.backend.RoomResultR\x06result\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\x8b\x01\n" +
	"\x15GameFinishedBroadcast\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bfinished\x18\x02 \x01(\bR\bfinished\x12=\n" +
	"\x06result\x18\x03 \x01(\v2%.hitsz.aircraftwar.backend.RoomResultR\x06result\"\xeb\x04\n" +
	"\tWsMessage\x12g\n" +
	"\x16player_heartbeat_event\x18\x01 \x01(\v2/.hitsz.aircraftwar.backend.PlayerHeartbeatEventH\x00R\x14playerHeartbeatEvent\x12^\n" +
	"\x13player_defeat_event\x18\x02 \x01(\v2,.hitsz.aircraftwar.backend.PlayerDefeatEventH\x00R\x11playerDefeatEvent\x12e\n" +
	"\x16player_game_over_event\x18\x03 \x01(\v2..hitsz.aircraftwar.backend.PlayerGameOverEventH\x00R\x13playerGameOverEvent\x12T\n" +
	"\x0fscore_broadcast\x18\x04 \x01(\v2).hitsz.aircraftwar.backend.ScoreBroadcastH\x00R\x0escoreBroadcast\x12j\n" +
	"\x17game_finished_broadcast\x18\x05 \x01(\v20.hitsz.aircraftwar.backend.GameFinishedBroadcastH\x00R\x15gameFinishedBroadcast\x12a\n" +
	"\x14room_state_broadcast\x18\x06 \x01(\v2-.hitsz.aircraftwar.backend.RoomStateBroadcastH\x00R\x12roomStateBroadcastB\t\n" +
	"\apayload*\xa2\x01\n" +
	"\n" +
	"RoomStatus\x12\x1b\n" +
	"\x17ROOM_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ROOM_STATUS_WAITING\x10\x01\x12\x14\n" +
	"\x10ROOM_STATUS_FULL\x10\x02\x12\x15\n" +
	"\x11ROOM_STATUS_READY\x10\x03\x12\x17\n" +
	"\x13ROOM_STATUS_PLAYING\x10\x04\x12\x18\n" +
	"\x14ROOM_STATUS_FINISHED\x10\x05*\x97\x01\n" +
	"\fPlayerStatus\x12\x1d\n" +
	"\x19PLAYER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PLAYER_STATUS_JOINED\x10\x01\x12\x17\n" +
	"\x13PLAYER_STATUS_READY\x10\x02\x12\x19\n" +
	"\x15PLAYER_STATUS_PLAYING\x10\x03\x12\x1a\n" +
	"\x16PLAYER_STATUS_FINISHED\x10\x04*f\n" +
	"\tEnemyType\x12\x1a\n" +
	"\x16ENEMY_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eENEMY_TYPE_MOB\x10\x01\x12\x14\n" +
	"\x10ENEMY_TYPE_ELITE\x10\x02\x12\x13\n" +
	"\x0fENEMY_TYPE_BOSS\x10\x03*\x81\x01\n" +
	"\x0eRoomDifficulty\x12\x1f\n" +
	"\x1bROOM_DIFFICULTY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ROOM_DIFFICULTY_EASY\x10\x01\x12\x1a\n" +
	"\x16ROOM_DIFFICULTY_NORMAL\x10\x02\x12\x18\n" +
	"\x14ROOM_DIFFICULTY_HARD\x10\x03*n\n" +
	"\x0eGameResultType\x12\x1b\n" +
	"\x17GAME_RESULT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fGAME_RESULT_WIN\x10\x01\x12\x14\n" +
	"\x10GAME_RESULT_LOSE\x10\x02\x12\x14\n" +
	"\x10GAME_RESULT_DRAW\x10\x03*\x82\x01\n" +
	"\x12PlayerFinishReason\x12$\n" +
	" PLAYER_FINISH_REASON_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPLAYER_FINISH_REASON_NORMAL\x10\x01\x12%\n" +
	"!PLAYER_FINISH_REASON_DISCONNECTED\x10\x02B5Z3github.com/acc1111/aircraft-war-hitsz/backend/pb;pbb\x06proto3"

var (
	file_proto_aircraft_war_proto_rawDescOnce sync.Once
	file_proto_aircraft_war_proto_rawDescData []byte
)

func file_proto_aircraft_war_proto_rawDescGZIP() []byte {
	file_proto_aircraft_war_proto_rawDescOnce.Do(func() {
		file_proto_aircraft_war_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aircraft_war_proto_rawDesc), len(file_proto_aircraft_war_proto_rawDesc)))
	})
	return file_proto_aircraft_war_proto_rawDescData
}

var file_proto_aircraft_war_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_aircraft_war_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_aircraft_war_proto_goTypes = []any{
	(RoomStatus)(0),                      // 0: hitsz.aircraftwar.backend.RoomStatus
	(PlayerStatus)(0),                    // 1: hitsz.aircraftwar.backend.PlayerStatus
	(EnemyType)(0),                       // 2: hitsz.aircraftwar.backend.EnemyType
	(RoomDifficulty)(0),                  // 3: hitsz.aircraftwar.backend.RoomDifficulty
	(GameResultType)(0),                  // 4: hitsz.aircraftwar.backend.GameResultType
	(PlayerFinishReason)(0),              // 5: hitsz.aircraftwar.backend.PlayerFinishReason
	(*Player)(nil),                       // 6: hitsz.aircraftwar.backend.Player
	(*Room)(nil),                         // 7: hitsz.aircraftwar.backend.Room
	(*RoomPlayerScore)(nil),              // 8: hitsz.aircraftwar.backend.RoomPlayerScore
	(*RoomResult)(nil),                   // 9: hitsz.aircraftwar.backend.RoomResult
	(*LeaderboardEntry)(nil),             // 10: hitsz.aircraftwar.backend.LeaderboardEntry
	(*CreateRoomRequest)(nil),            // 11: hitsz.aircraftwar.backend.CreateRoomRequest
	(*CreateRoomResponse)(nil),           // 12: hitsz.aircraftwar.backend.CreateRoomResponse
	(*JoinRoomRequest)(nil),              // 13: hitsz.aircraftwar.backend.JoinRoomRequest
	(*JoinRoomResponse)(nil),             // 14: hitsz.aircraftwar.backend.JoinRoomResponse
	(*ReadyRoomRequest)(nil),             // 15: hitsz.aircraftwar.backend.ReadyRoomRequest
	(*ReadyRoomResponse)(nil),            // 16: hitsz.aircraftwar.backend.ReadyRoomResponse
	(*UpdateRoomDifficultyRequest)(nil),  // 17: hitsz.aircraftwar.backend.UpdateRoomDifficultyRequest
	(*UpdateRoomDifficultyResponse)(nil), // 18: hitsz.aircraftwar.backend.UpdateRoomDifficultyResponse
	(*StartGameRequest)(nil),             // 19: hitsz.aircraftwar.backend.StartGameRequest
	(*StartGameResponse)(nil),            // 20: hitsz.aircraftwar.backend.StartGameResponse
	(*GetRoomResultRequest)(nil),         // 21: hitsz.aircraftwar.backend.GetRoomResultRequest
	(*GetRoomResultResponse)(nil),        // 22: hitsz.aircraftwar.backend.GetRoomResultResponse
	(*GetRoomStateRequest)(nil),          // 23: hitsz.aircraftwar.backend.GetRoomStateRequest
	(*GetRoomStateResponse)(nil),         // 24: hitsz.aircraftwar.backend.GetRoomStateResponse
	(*GetLeaderboardRequest)(nil),        // 25: hitsz.aircraftwar.backend.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil),       // 26: hitsz.aircraftwar.backend.GetLeaderboardResponse
	(*PlayerDefeatEvent)(nil),            // 27: hitsz.aircraftwar.backend.PlayerDefeatEvent
	(*PlayerHeartbeatEvent)(nil),         // 28: hitsz.aircraftwar.backend.PlayerHeartbeatEvent
	(*PlayerGameOverEvent)(nil),          // 29: hitsz.aircraftwar.backend.PlayerGameOverEvent
	(*ScoreBroadcast)(nil),               // 30: hitsz.aircraftwar.backend.ScoreBroadcast
	(*RoomStateBroadcast)(nil),           // 31: hitsz.aircraftwar.backend.RoomStateBroadcast
	(*GameFinishedBroadcast)(nil),        // 32: hitsz.aircraftwar.backend.GameFinishedBroadcast
	(*WsMessage)(nil),                    // 33: hitsz.aircraftwar.backend.WsMessage
}
var file_proto_aircraft_war_proto_depIdxs = []int32{
	1,  // 0: hitsz.aircraftwar.backend.Player.status:type_name -> hitsz.aircraftwar.backend.PlayerStatus
	0,  // 1: hitsz.aircraftwar.backend.Room.status:type_name -> hitsz.aircraftwar.backend.RoomStatus
	6,  // 2: hitsz.aircraftwar.backend.Room.players:type_name -> hitsz.aircraftwar.backend.Player
	3,  // 3: hitsz.aircraftwar.backend.Room.difficulty:type_name -> hitsz.aircraftwar.backend.RoomDifficulty
	1,  // 4: hitsz.aircraftwar.backend.RoomPlayerScore.status:type_name -> hitsz.aircraftwar.backend.PlayerStatus
	5,  // 5: hitsz.aircraftwar.backend.RoomPlayerScore.finish_reason:type_name -> hitsz.aircraftwar.backend.PlayerFinishReason
	4,  // 6: hitsz.aircraftwar.backend.RoomResult.self_result:type_name -> hitsz.aircraftwar.backend.GameResultType
	5,  // 7: hitsz.aircraftwar.backend.RoomResult.player_a_finish_reason:type_name -> hitsz.aircraftwar.backend.PlayerFinishReason
	5,  // 8: hitsz.aircraftwar.backend.RoomResult.player_b_finish_reason:type_name -> hitsz.aircraftwar.backend.PlayerFinishReason
	3,  // 9: hitsz.aircraftwar.backend.CreateRoomRequest.difficulty:type_name -> hitsz.aircraftwar.backend.RoomDifficulty
	7,  // 10: hitsz.aircraftwar.backend.CreateRoomResponse.room:type_name -> hitsz.aircraftwar.backend.Room
	6,  // 11: hitsz.aircraftwar.backend.CreateRoomResponse.self:type_name -> hitsz.aircraftwar.backend.Player
	7,  // 12: hitsz.aircraftwar.backend.JoinRoomResponse.room:type_name -> hitsz.aircraftwar.backend.Room
	6,  // 13: hitsz.aircraftwar.backend.JoinRoomResponse.self:type_name -> hitsz.aircraftwar.backend.Player
	7,  // 14: hitsz.aircraftwar.backend.ReadyRoomResponse.room:type_name -> hitsz.aircraftwar.backend.Room
	3,  // 15: hitsz.aircraftwar.backend.UpdateRoomDifficultyRequest.difficulty:type_name -> hitsz.aircraftwar.backend.RoomDifficulty
	7,  // 16: hitsz.aircraftwar.backend.UpdateRoomDifficultyResponse.room:type_name -> hitsz.aircraftwar.backend.Room
	7,  // 17: hitsz.aircraftwar.backend.StartGameResponse.room:type_name -> hitsz.aircraftwar.backend.Room
	9,  // 18: hitsz.aircraftwar.backend.GetRoomResultResponse.result:type_name -> hitsz.aircraftwar.backend.RoomResult
	7,  // 19: hitsz.aircraftwar.backend.GetRoomStateResponse.room:type_name -> hitsz.aircraftwar.backend.Room
	8,  // 20: hitsz.aircraftwar.backend.GetRoomStateResponse.scores:type_name -> hitsz.aircraftwar.backend.RoomPlayerScore
	9,  // 21: hitsz.aircraftwar.backend.GetRoomStateResponse.result:type_name -> hitsz.aircraftwar.backend.RoomResult
	10, // 22: hitsz.aircraftwar.backend.GetLeaderboardResponse.entries:type_name -> hitsz.aircraftwar.backend.LeaderboardEntry
	2,  // 23: hitsz.aircraftwar.backend.PlayerDefeatEvent.enemy_type:type_name -> hitsz.aircraftwar.backend.EnemyType
	8,  // 24: hitsz.aircraftwar.backend.ScoreBroadcast.scores:type_name -> hitsz.aircraftwar.backend.RoomPlayerScore
	7,  // 25: hitsz.aircraftwar.backend.RoomStateBroadcast.room:type_name -> hitsz.aircraftwar.backend.Room
	8,  // 26: hitsz.aircraftwar.backend.RoomStateBroadcast.scores:type_name -> hitsz.aircraftwar.backend.RoomPlayerScore
	9,  // 27: hitsz.aircraftwar.backend.RoomStateBroadcast.result:type_name -> hitsz.aircraftwar.backend.RoomResult
	9,  // 28: hitsz.aircraftwar.backend.GameFinishedBroadcast.result:type_name -> hitsz.aircraftwar.backend.RoomResult
	28, // 29: hitsz.aircraftwar.backend.WsMessage.player_heartbeat_event:type_name -> hitsz.aircraftwar.backend.PlayerHeartbeatEvent
	27, // 30: hitsz.aircraftwar.backend.WsMessage.player_defeat_event:type_name -> hitsz.aircraftwar.backend.PlayerDefeatEvent
	29, // 31: hitsz.aircraftwar.backend.WsMessage.player_game_over_event:type_name -> hitsz.aircraftwar.backend.PlayerGameOverEvent
	30, // 32: hitsz.aircraftwar.backend.WsMessage.score_broadcast:type_name -> hitsz.aircraftwar.backend.ScoreBroadcast
	32, // 33: hitsz.aircraftwar.backend.WsMessage.game_finished_broadcast:type_name -> hitsz.aircraftwar.backend.GameFinishedBroadcast
	31, // 34: hitsz.aircraftwar.backend.WsMessage.room_state_broadcast:type_name -> hitsz.aircraftwar.backend.RoomStateBroadcast
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_proto_aircraft_war_proto_init() }
func file_proto_aircraft_war_proto_init() {
	if File_proto_aircraft_war_proto != nil {
		return
	}
	file_proto_aircraft_war_proto_msgTypes[27].OneofWrappers = []any{
		(*WsMessage_PlayerHeartbeatEvent)(nil),
		(*WsMessage_PlayerDefeatEvent)(nil),
		(*WsMessage_PlayerGameOverEvent)(nil),
		(*WsMessage_ScoreBroadcast)(nil),
		(*WsMessage_GameFinishedBroadcast)(nil),
		(*WsMessage_RoomStateBroadcast)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aircraft_war_proto_rawDesc), len(file_proto_aircraft_war_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_aircraft_war_proto_goTypes,
		DependencyIndexes: file_proto_aircraft_war_proto_depIdxs,
		EnumInfos:         file_proto_aircraft_war_proto_enumTypes,
		MessageInfos:      file_proto_aircraft_war_proto_msgTypes,
	}.Build()
	File_proto_aircraft_war_proto = out.File
	file_proto_aircraft_war_proto_goTypes = nil
	file_proto_aircraft_war_proto_depIdxs = nil
}
